import { ArrowRight, Sparkles, Zap, Leaf } from 'lucide-react';
import Head from 'next/head';

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>ZenQuotes AI - Intelligent Quote Generator</title>
        <meta
          name="description"
          content="Generate original, thoughtful quotes powered by AI. Experience zen-like simplicity with ZenQuotes."
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="min-h-screen bg-gradient-to-b from-slate-950 via-green-950 to-slate-950">
        {/* Navigation */}
        <nav className="fixed top-0 w-full backdrop-blur-md bg-slate-950/80 z-50 border-b border-green-900/30">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-16">
            <div className="flex items-center gap-2">
              <Leaf className="w-6 h-6 text-green-400" />
              <span className="text-xl font-bold text-white">ZenQuotes AI</span>
            </div>
            <a
              href="https://github.com/Mrvatsan/Ai_Quotes_Generator"
              target="_blank"
              rel="noopener noreferrer"
              className="px-4 py-2 text-sm font-medium text-green-400 hover:text-green-300 transition-colors"
            >
              GitHub
            </a>
          </div>
        </nav>

        {/* Hero Section */}
        <section className="pt-32 pb-20 px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto text-center">
            <div className="inline-block mb-6 px-4 py-2 bg-green-900/30 rounded-full border border-green-700/50">
              <span className="text-sm text-green-300 font-medium">✨ Powered by Llama 3.3 AI</span>
            </div>

            <h1 className="text-5xl sm:text-6xl font-bold text-white mb-6 leading-tight">
              Find Inspiration in
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-green-400 to-emerald-400">
                Original AI Quotes
              </span>
            </h1>

            <p className="text-xl text-gray-300 mb-10 max-w-2xl mx-auto leading-relaxed">
              Generate thoughtful, original quotes instantly. Experience zen-like simplicity with our
              AI-powered quote generator designed for focus and inspiration.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a
                href="https://quotes-generator.streamlit.app/"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center gap-2 px-8 py-4 bg-gradient-to-r from-green-600 to-emerald-600 text-white font-semibold rounded-lg hover:from-green-500 hover:to-emerald-500 transition-all shadow-lg hover:shadow-xl transform hover:scale-105"
              >
                Try It Now
                <ArrowRight className="w-5 h-5" />
              </a>
              <a
                href="#features"
                className="inline-flex items-center justify-center px-8 py-4 border-2 border-green-600 text-green-400 font-semibold rounded-lg hover:bg-green-900/20 transition-all"
              >
                Learn More
              </a>
            </div>
          </div>

          {/* Hero Visual */}
          <div className="mt-20 max-w-3xl mx-auto">
            <div className="relative">
              <div className="absolute inset-0 bg-gradient-to-r from-green-600/20 to-emerald-600/20 rounded-2xl blur-3xl"></div>
              <div className="relative bg-slate-900/50 border border-green-900/30 rounded-2xl p-8 backdrop-blur-sm">
                <p className="text-gray-300 text-lg leading-relaxed italic">
                  "The mind finds peace when words become silence, and silence becomes wisdom."
                </p>
                <span className="text-sm text-green-400 mt-4 block">— Generated by ZenQuotes AI</span>
              </div>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="py-20 px-4 sm:px-6 lg:px-8 border-t border-green-900/30">
          <div className="max-w-6xl mx-auto">
            <h2 className="text-4xl font-bold text-white text-center mb-16">Why Choose ZenQuotes?</h2>

            <div className="grid md:grid-cols-3 gap-8">
              {/* Feature 1 */}
              <div className="bg-slate-900/50 border border-green-900/30 rounded-xl p-8 hover:border-green-700/60 transition-all hover:shadow-lg hover:shadow-green-900/20">
                <Sparkles className="w-10 h-10 text-green-400 mb-4" />
                <h3 className="text-xl font-bold text-white mb-3">AI-Powered</h3>
                <p className="text-gray-400">
                  Leverages Llama 3.3 70B via Groq for intelligent, original quote generation that feels
                  natural and inspiring.
                </p>
              </div>

              {/* Feature 2 */}
              <div className="bg-slate-900/50 border border-green-900/30 rounded-xl p-8 hover:border-green-700/60 transition-all hover:shadow-lg hover:shadow-green-900/20">
                <Zap className="w-10 h-10 text-green-400 mb-4" />
                <h3 className="text-xl font-bold text-white mb-3">Lightning Fast</h3>
                <p className="text-gray-400">
                  Generate 5 unique quotes in seconds. Experience instant inspiration without waiting or
                  unnecessary complexity.
                </p>
              </div>

              {/* Feature 3 */}
              <div className="bg-slate-900/50 border border-green-900/30 rounded-xl p-8 hover:border-green-700/60 transition-all hover:shadow-lg hover:shadow-green-900/20">
                <Leaf className="w-10 h-10 text-green-400 mb-4" />
                <h3 className="text-xl font-bold text-white mb-3">Zen Design</h3>
                <p className="text-gray-400">
                  A beautiful, minimal green theme designed for focus and tranquility. Clean, responsive,
                  and distraction-free.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Tech Stack Section */}
        <section className="py-20 px-4 sm:px-6 lg:px-8 border-t border-green-900/30">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold text-white text-center mb-12">Built With Modern Tech</h2>

            <div className="grid sm:grid-cols-2 gap-6">
              <div className="bg-slate-900/50 border border-green-900/30 rounded-lg p-6">
                <h3 className="text-green-400 font-semibold mb-3">Frontend</h3>
                <ul className="space-y-2 text-gray-400">
                  <li>• Streamlit (Python) - Main application</li>
                  <li>• Next.js/React - Web interface</li>
                  <li>• Tailwind CSS - Styling</li>
                </ul>
              </div>

              <div className="bg-slate-900/50 border border-green-900/30 rounded-lg p-6">
                <h3 className="text-green-400 font-semibold mb-3">Backend & AI</h3>
                <ul className="space-y-2 text-gray-400">
                  <li>• Groq SDK - LLM inference</li>
                  <li>• Llama 3.3 70B - AI model</li>
                  <li>• Python Dotenv - Configuration</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-20 px-4 sm:px-6 lg:px-8 border-t border-green-900/30">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-4xl font-bold text-white mb-6">Ready to Find Inspiration?</h2>
            <p className="text-xl text-gray-300 mb-10">
              Start generating original, thoughtful quotes in seconds.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a
                href="https://quotes-generator.streamlit.app/"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center gap-2 px-8 py-4 bg-gradient-to-r from-green-600 to-emerald-600 text-white font-semibold rounded-lg hover:from-green-500 hover:to-emerald-500 transition-all shadow-lg hover:shadow-xl transform hover:scale-105"
              >
                Launch App
                <ArrowRight className="w-5 h-5" />
              </a>
              <a
                href="https://github.com/Mrvatsan/Ai_Quotes_Generator"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center px-8 py-4 border-2 border-green-600 text-green-400 font-semibold rounded-lg hover:bg-green-900/20 transition-all"
              >
                View Source
              </a>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="border-t border-green-900/30 py-8 px-4 sm:px-6 lg:px-8">
          <div className="max-w-6xl mx-auto text-center text-gray-400">
            <p>
              © 2024 ZenQuotes AI. Built by{' '}
              <a
                href="https://github.com/Mrvatsan"
                target="_blank"
                rel="noopener noreferrer"
                className="text-green-400 hover:text-green-300 transition-colors"
              >
                Mrvatsan
              </a>
              . Licensed under MIT.
            </p>
          </div>
        </footer>
      </div>
    </>
  );
}
